[bastion]
13.38.71.17

[traefik]
10.0.1.98

[managers]
10.0.2.182
10.0.2.20
10.0.2.42

[workers]
10.0.2.193
10.0.2.154

[monitoring]
10.0.2.84

[swarm:children]
managers
workers

[private:children]
managers
workers
monitoring
traefik
