[bastion]
35.180.187.118

[traefik]
10.0.1.46

[managers]
10.0.2.109
10.0.2.206
10.0.2.16

[workers]
10.0.2.95
10.0.2.78

[monitoring]
10.0.2.185

[swarm:children]
managers
workers

[private:children]
managers
workers
monitoring
traefik
