# Généré automatiquement par Terraform — ne pas modifier manuellement
ansible_user: ubuntu
ansible_ssh_private_key_file: ~/.ssh/gitea-project
efs_dns_name: "fs-04b2ba892eb233466.efs.eu-west-3.amazonaws.com"
rds_endpoint: "gitea-prod-db.cd0ycauugwkd.eu-west-3.rds.amazonaws.com:5432"
traefik_public_ip: "15.237.185.235"
monitoring_ip: "10.0.2.84"
