name: Lint

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  terraform:
    name: Terraform validate
    runs-on: ubuntu-latest

    strategy:
      matrix:
        env: [prod, staging]

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform init (${{ matrix.env }})
        working-directory: terraform/envs/${{ matrix.env }}
        run: terraform init -backend=false

      - name: Terraform validate (${{ matrix.env }})
        working-directory: terraform/envs/${{ matrix.env }}
        run: terraform validate

      - name: Terraform fmt check (${{ matrix.env }})
        working-directory: terraform/envs/${{ matrix.env }}
        run: terraform fmt -check -recursive
